var GAME_LEVELS = [
  ["                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                          
   "                  xnnnnnnnnnnnnnnnnnnnn                 y                      x",
   "                  x                                     v                      x",
   "                  x                                                            x",
   "                  x                                                            x",
   "                  x                         l     ooo         oo               x",
   "                  x                                                   ooo      x",
   "  xxxxxxxxxxxxxxxxx                               xxxx                         x",
   "  xnnn     y                         ooo      xx           xxxx        xxx     x",
   "  x        v          oo                                                       x",
   "  x                                    xxxxx                                   x",
   "  x                                                                            x",
   "  x                                                                            x",
   "  x  o           xxxxx           y                               xxxx          x",
   "  x              x   x           v  xx                                         x",
   "  x         xxx  x   x                                                         x",
   "  x   @     x x!!x   x                           y=               y            x",
   "  xxxxxxxxxxx xxxx   xxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxx",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     xxxxx             ",
   "                         xxxxxxx                  xxxxxxx                       ",
   "                                                                                ",
   "                                                                                "],
  ["                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                      x  y     y                                      xnnnnnnn            x",
   "                      x  v     v                     l                x                   x",
   " xxxxxxxxxxxxxxxxxxxxxx                                               x                   x",
   " xnnnnnn   y          x                         xxxxxxxxxxx           x                o  x",
   " x         v          x o   o    o              x         x  o        x                   x",
   " x                    x                         x         x           x               xx  x",
   " x                    xxxxxxxxxxxxxx            x         x           x         xxxx      x",
   " x                    xnnnn                 xxxxx         xxxxxx      x            x      x",
   " x                                              x              x      xxxxxx       x      x",
   " x               y                              x              x      x         o  x      x",
   " x               v                      xx      x              x      x            x      x",
   " x                         oo                   x              x      x        xxxxx      x",
   " x                                              x              x      x            x      x",
   " x                                              x              x      xxxx         x      x",
   " x     y                                        x              x  o      x  oo     x!!!!!!x",
   " x     v           xxx       xxxxxx    xxxxx    x              x  o      x         x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x              x  o      xxxxx     x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x              x         x         x!!!!!!x",
   " x         ooo               x    x!!!!x   x!!!!x              xxxx      x       o x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x              xy=     o x         x!!!!!!x",
   " x        xxxxxx      xxxxxxxx    x!!!!x   x!!!!x              x         x      xxxx!!!!!!x",
   " x        x    x!!!!!!x           x!!!!x   x!!!!x              x       xxx         x!!!!!!x",
   " x        x    x!!!!!!x           x!!!!x   x!!!!x              x        y          x!!!!!!x",
   " x   @    x    x!!!!!!x           x!!!!x   x!!!!x              x        v          x!!!!!!x",
   " xxxxxx   x    x!!!!!!x           x!!!!x   x!!!!x              x              xxx  x!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
   " xxxxxxxxxx    xxxxxxxxx          xxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                           ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxx  y             y          xnnn                        vv          x",
   " xnnn            y    x  v             v        o x            oo                  oo     x",
   " x               v    x                           x                     oo                x",
   " x                    x                        xxxx                                       x",
   " x                    x                           x           xxx                         x",
   " x             oo   o x                           x   xxx               xxxxxxxxxxxxxxxxxxx",
   " x    x               x               xxxx        x                            xnnnnnnnnnnx",
   " x  @ x     xxxxxxxxxxx                           xy=                o                    x",
   " x    x     x               l                     x                  xx                   x",
   " x  xxx   xxx      o                        xxxxxxx        oo                             x",
   " x    x     x     xxxxxxxxxxxxxxxxx         xnn                                           x",
   " x    x o   x       xn            v         x            xxxxx             xxx            x",
   " x    x     x       x                  xxxxxx                                             x",
   " x    xxx   x       x                                                            xxxx     x",
   " x    x     x       x                                x             x    x    x   x y      x",
   " x    x     xxxx    x             xxxx    xxxxxxxx!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!x v      x",
   " x    x     x       x                     x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x      xxx",
   " x    x   o x       xxxxxxxx              x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x   xxx    xxxxy=                   x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x     x       x     o   o   o       x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x     x       xxxxxxxxxxxxxxxxxxxxxxx      x!!!!!!!!x     x!!!!!!!!!!!!!!!!xxx      x",
   " x    x     x                             x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x     xxxxxx                        x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x     xnnnnn                        x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x     x!!x",
   " x    x                                   x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x     x!!x",
   " x    x       xxxxxxxxxxxxxxxxxxxxxxxx    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x     x!!x",
   " x    x       x  vv    vv    vv      x    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!xx    x!!x",
   " x    xxx     x                      x    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x     x!!x",
   " x    x                              x  o x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x      !!x",
   " x    x    xx                             x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x",
   " x    x!!!!!x       o      o     o        x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x o o  o x",
   " x!!!!x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                            ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x                                                  o                            o         x",
   " x                                                                                         x",
   " xl                               ooo        y=           y            y=          y       x",
   " x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x",
   " xxxxx                                                       xnn                           x",
   " x                           o                               x                          xxxx",
   " xy=                                                        yx                             x",
   " x                   n                 n                     x                             x",
   " xxxxxxy=                                                    x     xx!!xxx!!xxx!!xxx!!xxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x                        nnnnnx",
   " xnnnn                 y                  xnnnnnnx         xxx                           =yx",
   " x                     v                         x o         x o                     n     x",
   " x                                               x           x                             x",
   " x      oo                                       xxxx        x              o            =yx",
   " x                                                         n xxxxxxxxxx    xxx             x",
   " x     xxxx                                                  x!!!!!!!!!                    x",
   " xx    x  x                                              xxxxx!!!!!!!!!                    x",
   " x     x  x                                                  x!!!!!!!!!          xxxx    o x",
   " x     x  xxxxx                                              x!!!!!!!!!                    x",
   " x    xx  x!!!x        x          x          x               x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x     xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx",
   " x  @  x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx",
   " xxxxxxx  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   " x!!!!!x  x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x!!!!!x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
