var GAME_LEVELS = [
  ["                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                          
   "                  x                                     y                      x",
   "                  x                                     v                      x",
   "                  x                                                            x",
   "                  x                                                            x",
   "                  x                         l     ooo         oo               x",
   "                  x                                                   ooo      x",
   "  xxxxxxxxxxxxxxxxx                               xxxx                         x",
   "  x        y                         ooo      xx           xxxx        xxx     x",
   "  x        v          oo                                                       x",
   "  x                                    xxxxx                                   x",
   "  x                                                                            x",
   "  x                n                                                           x",
   "  x  o           xxxxx           y                               xxxx          x",
   "  x              x   x           v  xx                                         x",
   "  x         xxx  x   x                                                         x",
   "  x   @     x x!!x   x                           y=               y            x",
   "  xxxxxxxxxxx xxxx   xxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxx",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     xxxxx             ",
   "                         xxxxxxx                  xxxxxxx                       ",
   "                                                                                ",
   "                                                                                "],
  ["                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                      x  y     y                                           x                   x",
   "                      x  v     v                                           x                   x",
   " xxxxxxxxxxxxxxxxxxxxxx                                                    x                   x",
   " x         y          x                         xxxxxxxxxxx                x                o  x",
   " x         v          x o   o    o              x         x  o             x   l               x",
   " x                    x                         x         x                x               xx  x",
   " x                    xxxxxxxxxxxxxx            x         x                x         xxxx      x",
   " x                                          xxxxx         xxxxxxxxxxx      x            x      x",
   " x                                              x                   x      xxxxxx       x      x",
   " x               y                              x                   x      x         o  x      x",
   " x               v                      xx      x                   x      x            x      x",
   " x                         oo                   x                   x      x        xxxxx      x",
   " x                                              x                   x      x            x      x",
   " x                                              x                   x      xxxx         x      x",
   " x     y                                        x                   x  o      x  oo     x!!!!!!x",
   " x     v           xxx       xxxxxx    xxxxx    x                   x  o      x         x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x                   x  o      xxxxx     x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x                   x         x         x!!!!!!x",
   " x         ooo          n    x    x!!!!x   x!!!!x                   xxxx      x       o x!!!!!!x",
   " x                           x    x!!!!x   x!!!!x                   xy=     o x         x!!!!!!x",
   " x        xxxxxx      xxxxxxxx    x!!!!x   x!!!!x                   x         x      xxxx!!!!!!x",
   " x        x    x!!!!!!x           x!!!!x   x!!!!x                   x       xxx         x!!!!!!x",
   " x        x    x!!!!!!x           x!!!!x   x!!!!x                   x        y          x!!!!!!x",
   " x   @    x    x!!!!!!x           x!!!!x   x!!!!x                   x        v          x!!!!!!x",
   " xxxxxx   x    x!!!!!!x           x!!!!x   x!!!!x                   x              xxx  x!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x                   x              x!!!!!!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x                   x n            x!!!!!!!!!!!x",
   " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x                   x              x!!!!!!!!!!!x",
   " xxxxxxxxxx    xxxxxxxxx          xxxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxx  y             y          x                                vv          x",
   " x               y    x  v             v        o x            oo                       oo   l x",
   " x               v    x                           x                          oo                x",
   " x                    x                        xxxx                                            x",
   " x                    x                           x           xxx                              x",
   " x             oo   o x                           x   xxx                  xxxxxxxxxxxxxxxxxxxxx",
   " x    x               x               xxxx        x                                            x",
   " x  @ x     xxxxxxxxxxx                           xy=                o                         x",
   " x    x     x                                     x                  xx                 n      x",
   " x  xxx   xxx      o                        xxxxxxx        oo                                  x",
   " x    x     x     xxxxxxxxxxxxxxxxx         x                                                  x",
   " x    x o   x       x             v         x            xxxxx             xxx                 x",
   " x    x     x       x                  xxxxxx                                                  x",
   " x    xxx   x       x                                                            xxxxxxx       x",
   " x    x     x       x                                x             x    x    x   x  y          x",
   " x    x     xxxx    x   n         xxxx    xxxxxxxx!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!x  v          x",
   " x    x     x       x                     x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x          xxxx",
   " x    x   o x       xxxxxxxx              x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x             x",
   " x    x   xxx    xxxxy=                   x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x             x",
   " x    x     x       x     o   o   o       x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x             x",
   " x    x     x       xxxxxxxxxxxxxxxxxxxxxxx      x!!!!!!!!x     x!!!!!!!!!!!!!!!!xxxxxxxx    s x",
   " x    x     x                             x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x             x",
   " x    x     x                             x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        xxxxxx",
   " x    x     xxxxxx                        x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x!!!!x",
   " x    x                      n            x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x        x!!!!x",
   " x    x       xxxxxxxxxxxxxxxxxxxxxxxx    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x         !!!!x",
   " x    x       x  vv    vv    vv      x    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!xxxx      !!!!x",
   " x    xxx     x                      x    x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x         !!!!x",
   " x    x                              x  o x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x         !!!!x",
   " x    x    xx                             x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x             x",
   " x    x!!!!!x       o      o     o        x      x!!!!!!!!x     x!!!!!!!!!!!!!!!!x     o  o  o x",
   " x!!!!x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                 ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x                                                  o                            o              x",
   " x                                                                                              x",
   " xl                               ooo        y=           y            y=                y      x",
   " x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x",
   " xxxxx                                                       x                                  x",
   " x                           o                               x                               xxxx",
   " xy=                                                        yx                             o    x",
   " x                   n                 n                     x                                  x",
   " xxxxxxy=                                                    x     xx!!xxx!!xxx!!xxx!!xxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x                                  x",
   " x                     y                         x         xxx                                =yx",
   " x                     v                         x o         x o                     n          x",
   " x                                               x           x                                  x",
   " x      oo                                       xxxx        x              o                 =yx",
   " x                                                         n xxxxxxxxxx    xxx                  x",
   " x     xxxx                                                  x!!!!!!!!!                        x",
   " xx    x  x                                              xxxxx!!!!!!!!!                        x",
   " x     x  x                                                  x!!!!!!!!!          xxxx        o x",
   " x     x  xxxxx                                              x!!!!!!!!!                        x",
   " x    xx  x!!!x        x          x          x               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x     xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " x  @  x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " x     x  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " xxxxxxx  x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!x!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   " x!!!!!x  x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x!!!!!x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
